### ISSUE TITLE
Edge not supported

### ISSUE THREAD

**Issue by jgvega** [SagarMaheshwary/webpush-example#2]
Edge generates a 401 character url key.
Mysql does not work with single key fields longer than 255 characters.
I made some changes to your code.
In migration use this:
"$ table-> charset = 'utf8';
            $ table-> collation = 'utf8_unicode_ci';
$ table-> increments ('id');
            $ table-> morphs ('subscribable');
            $ table-> string ('endpoint', 1000);
$ table-> string ('endpoint_key', 255) -> unique ();
            $ table-> string ('public_key') -> nullable ();
            $ table-> string ('auth_token') -> nullable ();
            $ table-> string ('content_encoding') -> nullable ();
            $ table-> timestamps (); "

Other modifications in:
HasPushSubscriptions.php

and
PushSubscription.php

and I used a hash algorithm to create the content of endpoint_key

**Comment by SagarMaheshwary** [comment]
Then we would have to check the uniqueness before storing it to the database since 255 is the max length of a unique key.

**Comment by jgvega** [comment]
'<?php

namespace NotificationChannels\WebPush;

trait HasPushSubscriptions
{
    /**
     *  Get all of the subscriptions.
     *
     * @return \Illuminate\Database\Eloquent\Relations\MorphMany
     */
    public function pushSubscriptions()
    {
        return $this->morphMany(config('webpush.model'), 'subscribable');
    }

    /**
     * Update (or create) subscription.
     *
     * @param  string $endpoint
     * @param  string $endpoint_key
     * @param  string|null $key
     * @param  string|null $token
     * @param  string|null $contentEncoding
     * @return \NotificationChannels\WebPush\PushSubscription
     */
    public function updatePushSubscription($endpoint,$endpoint_key, $key = null, $token = null, $contentEncoding = null)
    {
       // $subscription = app(config('webpush.model'))->findByEndpoint($endpoint);
        $subscription = app(config('webpush.model'))->findByEndpoint($endpoint_key);

        if ($subscription && $this->ownsPushSubscription($subscription)) {
            $subscription->public_key = $key;
            $subscription->auth_token = $token;
            $subscription->content_encoding = $contentEncoding;
            $subscription->save();

            return $subscription;
        }

        if ($subscription && ! $this->ownsPushSubscription($subscription)) {
            $subscription->delete();
        }

        return $this->pushSubscriptions()->create([
            'endpoint' => $endpoint,
            'endpoint_key' => $endpoint_key,
            'public_key' => $key,
            'auth_token' => $token,
            'content_encoding' => $contentEncoding,
        ]);
    }

    /**
     * Determine if the model owns the given subscription.
     *
     * @param  \NotificationChannels\WebPush\PushSubscription $subscription
     * @return bool
     */
    public function ownsPushSubscription($subscription)
    {
        return (string) $subscription->subscribable_id === (string) $this->getKey() &&
                        $subscription->subscribable_type === $this->getMorphClass();
    }

    /**
     * Delete subscription by endpoint.
     *
     * @param  string $endpoint
     * @return void
     */
   /* public function deletePushSubscription($endpoint)
    {
        $this->pushSubscriptions()
            ->where('endpoint', $endpoint)
            ->delete();
    }*/
    public function deletePushSubscription($endpoint_key)
    {
        $this->pushSubscriptions()
            ->where('endpoint_key', $endpoint_key)
            ->delete();
    }

    /**
     * Get all of the subscriptions.
     *
     * @return \Illuminate\Database\Eloquent\Collection
     */
    public function routeNotificationForWebPush()
    {
        return $this->pushSubscriptions;
    }
}'

**Comment by jgvega** [comment]
`<?php

namespace NotificationChannels\WebPush;

use Illuminate\Database\Eloquent\Model;

/**
 * @property string $endpoint
 * @property string|null $public_key
 * @property string|null $auth_token
 * @property string|null $content_encoding
 * @property \Illuminate\Database\Eloquent\Model $subscribable
 */
class PushSubscription extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'endpoint',
        'endpoint_key',
        'public_key',
        'auth_token',
        'content_encoding',
    ];

    /**
     * Create a new model instance.
     *
     * @param  array $attributes
     * @return void
     */
    public function __construct(array $attributes = [])
    {
        if (! isset($this->connection)) {
            $this->setConnection(config('webpush.database_connection'));
        }

        if (! isset($this->table)) {
            $this->setTable(config('webpush.table_name'));
        }

        parent::__construct($attributes);
    }

    /**
     * Get the model related to the subscription.
     *
     * @return \Illuminate\Database\Eloquent\Relations\MorphTo
     */
    public function subscribable()
    {
        return $this->morphTo();
    }

    /**
     * Find a subscription by the given endpint.
     *
     * @param  string $endpoint
     * @return static|null
     */
    /*public static function findByEndpoint($endpoint)
    {
        return static::where('endpoint', $endpoint)->first();
    }*/
    public static function findByEndpoint($endpoint_key)
    {
        return static::where('endpoint_key', $endpoint_key)->first();
    }
}
`

**Comment by jgvega** [comment]
`<?php

namespace App\Http\Controllers;
use Illuminate\Http\Request;
use App\Notifications\PushDemo;
use App\User;
use Auth;
use Notification;

class PushController extends Controller
{

    public function __construct(){
      $this->middleware('auth');
    }

    /**
     * Store the PushSubscription.
     * 
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function store(Request $request){
        $this->validate($request,[
            'endpoint'    => 'required',
            'keys.auth'   => 'required',
            'keys.p256dh' => 'required'
        ]);
        $endpoint = $request->endpoint;
        $endpoint_key = md5($request->endpoint);
        $token = $request->keys['auth'];
        $key = $request->keys['p256dh'];
        $user = Auth::user();
   
        $user->updatePushSubscription($endpoint,$endpoint_key, $key, $token);
        
        return response()->json(['success' => true],200);
    }
    public function remove(Request $request){
        $this->validate($request,[
            'endpoint'    => 'required',
            'keys.auth'   => 'required',
            'keys.p256dh' => 'required'
        ]);
        $endpoint = $request->endpoint;
        $endpoint_key = md5($request->endpoint);
        $token = $request->keys['auth'];
        $key = $request->keys['p256dh'];
        $user = Auth::user();
   
        $user->deletePushSubscription($endpoint_key);
        
        return response()->json(['success' => true],200);
    }
    public function push(){
        Notification::send(User::all(),new PushDemo());
        return redirect()->back();
    }
    
}`

**Comment by jgvega** [comment]
These are my modifications of your code.
This way it works on Edge, Chrome and Firefox desktop.
On Android it works with Chrome and Firefox.

**Comment by SagarMaheshwary** [comment]
Great!
