### ISSUE TITLE
its not showing notification popup in chrome 

### ISSUE THREAD

**Issue by ranksol1** [SagarMaheshwary/webpush-example#3]
can you check why its not showing popup notification in chrome?
https://scaleshike.com/webpush-demo/

**Comment by SagarMaheshwary** [comment]
Your demo is working fine on my device: ubuntu 20.04, chrome 90

**Comment by ranksol1** [comment]
can you share the screenshot of received notification in chrome ?
and on windows too, if possible 
thanks

**Comment by SagarMaheshwary** [comment]
![Screenshot from 2021-04-19 23-07-03](https://user-images.githubusercontent.com/31599124/115282896-2c7b1f00-a164-11eb-9362-e62238474f04.png)

**Comment by SagarMaheshwary** [comment]
Just delete your old endpoints from table which might be causing issues.

**Comment by ranksol1** [comment]
I did that but it not working on my window's chrome but working on my Android mobile.
thanks for your response 
appreciated your help and this repo
